### ISSUE TITLE
Stella/Comet/Spirit doesn't show measured temperature (SDKv2) 

### ISSUE THREAD

**Issue by konradwalsh** [caseda/org.eurotronic#15] opened 2019-01-16 17:31 UTC
I just got 2 spirit stats.. Neither are showing the current temperature.

I also Opened an issue for the Stella Z with the same issue

**Comment by caseda** [comment] 2019-01-16 17:42
I have not been able to reproduce this, so a bit hard to debug as it is using the normal implementation of the measure temperature capability all other temperature measuring devices use.
So I highly doubt it is an app issue

**Comment by caseda** [comment] 2019-01-16 17:45
Please check the zwave log if you ever receive any temperature signals from your devices

**Comment by caseda** [comment] 2019-01-21 08:17
Bump for what I asked for 5 days ago

**Comment by konradwalsh** [comment] 2019-01-21 08:33
So I am still testing to figure it out but did my back in (Not whilst testing 👅 😃 )

I have the Spirits working.. but still trying to get the Stella Z working..

This is what I did though..
Repeatedly removed the Z Wave Device method to try and factory reset them. Re-added them and no joy.

I removed the devices
I removed the app
I reinstalled the app
I added one device
Turned on the heating system to create as much temperature difference as possible
Got it working.

For Spirit no 2.. I did the above process three times and it worked but then had to add Spirit no 1 and that works fine now..

Started with Stella and still cannot get the above procedure to work with it.

I know turning on the heating has nothing to do with it really.. since it reports .1 degree diff.. but I am just detailing the sequence I went through

**Comment by caseda** [comment] 2019-01-21 10:03
Thanks for confirming that it isn't an app issue. 
As they all use the same way to report the current measured temperature, it is most likely a range/homey issue.

**Comment by konradwalsh** [comment] 2019-01-21 18:44
This should be close enough?

![21012019_184008](https://user-images.githubusercontent.com/7996482/51493231-9b624580-1dac-11e9-8a66-c7d40836d081.jpg)

**Comment by caseda** [comment] 2019-01-24 22:21
keep me up to date if it starts working, since 2.0.1 the latest meshdriver was added, though not much should have changed in measuring temperature, but also should just work.

Internally also some stability fixes has been added in v2.0.2, even though they don't directly were for measured temperature, more stable is always better for other signals.

it isn't much more I can do in the app though.

**Comment by caseda** [comment] 2019-05-04 18:24
Should have been fixed now.

**Closed by caseda** 2019-05-04 18:24 UTC
