### ISSUE TITLE
Spirit Status Off not picked up in flow

### ISSUE THREAD

**Issue by ronald2404** [caseda/org.eurotronic#11] opened 2018-11-14 07:44 UTC
Hi, I would like to create a flow that checks every 5 minutes all valves if there is a status Off. If all has the status Off  the Heating can go off. This doesn't work so i tried with just one valve. Doesn't work either. I included the status of the Valve in the screenshot so you can see the status is actually off. Also tried other valve, but same result. (if this works i would like tho create another flow with opposite function)

Homey Firmware Versie: 1.5.13-rc.14
and latest spirit app

Regards

Ronald

![image](https://user-images.githubusercontent.com/37141942/48467320-d4000480-e7e8-11e8-8528-5cc7f8a34aa7.png)

**Comment by caseda** [comment] 2018-11-14 08:10
Duplicate of #10

**Closed by caseda** 2018-11-14 08:10 UTC
